1.Write a Python Program to Add Two Matrices?

In [4]:
import numpy as np
a = np.matrix('1 2 3; 4 5 6; 7 8 9')
b = np.matrix('10 2 30; 14 5 16; 72 8 79')
print("Addition of Matrix : \n",a+b)

Addition of Matrix : 
 [[11  4 33]
 [18 10 22]
 [79 16 88]]


2.Write a Python Program to Multiply Two Matrices?

In [5]:
import numpy as np
a = np.matrix('1 2 3; 4 5 6; 7 8 9')
b = np.matrix('10 2 30; 14 5 16; 72 8 79')
print("Multiplication of Matrix : \n",a*b)

Multiplication of Matrix : 
 [[ 254   36  299]
 [ 542   81  674]
 [ 830  126 1049]]


3.Write a Python Program to Transpose a Matrix?

In [12]:
import numpy as np
a = np.matrix('1 2 3; 4 5 6; 7 8 9')
print("Transpose of Matrix : \n",a.transpose())


Transpose of Matrix : 
 [[1 4 7]
 [2 5 8]
 [3 6 9]]


4.Write a Python Program to Sort Words in Alphabetic Order?

In [21]:
lst = ['jeet','is','the','am','an']
lst.sort()
print("The sorted words are:")
for e in lst:
    print(e)

The sorted words are:
am
an
is
jeet
the


5.Write a Python Program to Remove Punctuation From a String?

In [26]:
punctuations = '''!()-[]{};:'"\,<>./?@#$%^&*_~'''
s = input("Please Enter a string with Punctuations : ")
n =''
for c in s:
    if c not in punctuations:
        n +=c
print("String After removing Punctuations : ",n)

Please Enter a string with Punctuations : Hello!!!, he said ---and went.
String After removing Punctuations :  Hello he said and went
